### ISSUE TITLE
spark history server

### ISSUE THREAD

**Issue by mkscala** [dylanmei/docker-zeppelin#8]
I wanted to add the Spark History server to view the logs and execution. Is is possible ?

**Comment by dylanmei** [comment]
When there is a running Spark context, the Spark Application UI is accessible via port 4040.

So, in using a simple docker-compose, ensure 4040 is being published:

```
zeppelin:
  image: dylanmei/zeppelin
  environment:
    ZEPPELIN_PORT: 8080
    MASTER: local[*]
  ports:
    - 8080:8080
    - 4040:4040
```

The Spark History server is something else entirely and not something I want to take on here.
